trainer:
  resume: true
  checkpoint: "checkpoints/xtts2/dvae.pth"
  mel_norm_file: "checkpoints/xtts2/mel_stats.pth"
  min_lr: 1e-6
  learning_rate: 5e-6
  epochs: 100
  log_interval: 100
  val_interval: 2000
  save_interval: 5000
  output_dir: "output/dvae"

dataset:
  train_file_list: "data/libritts/libritts_train.txt"
  valid_file_list: "data/libritts/libritts_valid.txt"
  sample_rate: 22050
  max_duration: 12.0
  num_workers: 32
  batch_size: 256

model:
  channels: 80
  normalization: null
  positional_dims: 1
  num_tokens: 1024
  codebook_dim: 512
  hidden_dim: 512
  num_resnet_blocks: 3
  kernel_size: 3
  num_layers: 2
  use_transposed_convs: false